modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="apvaulthuntersmod"
version="1.0.0"
displayName="AP Vault Hunters"
authors="StudMuffin"
description='''Archipelago integration for Vault Hunters'''

[[dependencies.apvaulthuntersmod]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.apvaulthuntersmod]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"

[[dependencies.apvaulthuntersmod]]
modId="the_vault"
mandatory=true
versionRange="*"
ordering="AFTER"
side="BOTH"

[[mixins]]
config = "vhap.mixins.json"